import pool from "@/lib/db";
import { Settings, Templates } from "@/types/GlobalsTypes";
import { SettingsQuery } from "@/types/serverTypes";
import { unstable_cache as cache } from "next/cache";

/**
 * Creates setting table with default values if it does not exist on database.
 * @author Siavash Araghi
 */
const createInitialSettingTable = async () => {
  try {
    const CREATE_TABLE_SQL = `
      CREATE TABLE IF NOT EXISTS settings (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        template_name VARCHAR(50) NOT NULL UNIQUE DEFAULT 'Primary',
        create_time TIMESTAMP NOT NULL DEFAULT NOW(),
        active BOOLEAN NOT NULL DEFAULT TRUE
      );
      INSERT INTO settings (template_name, active) SELECT 'Primary', TRUE WHERE NOT EXISTS (SELECT 1 FROM settings);
    `;
    await pool.query(CREATE_TABLE_SQL);
    return true;
  } catch (error) {
    console.log(error);
    return error;
  }
};

createInitialSettingTable();

const InitialSettingsValue: Settings = {
  id: 1,
  createTime: "",
  templateName: Templates.default,
  active: true,
};

export const getSettings = cache(async (): Promise<Settings> => {
  try {
    const GET_SETTINGS_QUERY = "SELECT * FROM settings WHERE active=true";
    const SETTING = (await pool.query(GET_SETTINGS_QUERY))
      .rows[0] as SettingsQuery;

    const {
      id,
      active,
      create_time: createTime,
      template_name: templateName,
    } = SETTING;
    return { id, active, createTime, templateName };
  } catch (error) {
    console.log(error);
    return InitialSettingsValue;
  }
}, ["template-settings"]);


/**
 * @author Siavash Araghi
 * @returns General data of website
 */
export const getGeneral = async () => {
  "use cache"
  try {
    const GENERAL_QUERY = "SELECT * FROM general;";
    const GENERAL_DATA = (await pool.query(GENERAL_QUERY)).rows;

    return GENERAL_DATA[0];
  } catch (error) {
    console.log("An error occured : " + error);
    return null;
  }
};
